name: PHP Composer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml
          tools: composer, phpmd, phpcs, php-cs-fixer

      - name: Composer update
        run: composer update --no-progress

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPMD
        run: phpmd . text cleancode,codesize,naming

      - name: Run PHPCS
        run: phpcs --standard=phpcs.xml .

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --config=.php-cs-fixer.php
